# Site settings
title: "想去抓鱼的土拨鼠"
description: "啊~~~~~~~~"
baseurl: ""
url: "https://yingjundeng.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "首页"
    url: /index
  - title: "其他"
    url: /view/other
  - title: "关于"
    url: /view/about
  - title: "一个女孩"
    url: /view/reson
  - title: "个人"
    url: /view/reson
