# Site settings
title: "想去抓鱼的土拨鼠"
description: "啊~~~~~~~~"
baseurl: ""
url: "https://yingjundeng.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "首页"
    url: /about
  - title: "其他"
    url: http://www.baidu.com
  - title: "关于"
    url: http://www.baidu.com
  - title: "个人"
    url: /feed.xml
